### ISSUE TITLE
Check PartialEq hangs indefinitely

### ISSUE THREAD

**Issue by broomlytinum** [QnnOkabayashi/strck#2]
The following code seems to hang indefinitely:

```rust
let this = "this".check::<NoInvariant>().unwrap(); // `chk` is fine though
assert_eq!(this, this);
```

I haven't been able to understand the implementations of `PartialEq` at a glance, but my first guess would be that it's some sort of cycle in `AsRef<str>` autoderef. I'll investigate further later.

**Comment by bobozaur** [comment]
This was indeed related to the `PartialEq` impl. It was `self == other`, which practically made it recursive. Created #3 which fixes this and adds tests to back it up.
